### ISSUE TITLE
Planning Japa version 3

### ISSUE THREAD

**Issue by thetutlage** [japa/runner#30]
Its been more than a year since we released Japa v2 (a rewrite). Now, we have collected some ideas and a plan to migrate to ESM, so it feels like the perfect moment for v3.

> **Note**: Migrating from Japa v2 to v3 will be relatively simple, with the only exception of moving from CJS to ESM. If your apps are already in ESM, then migrating should be a few minutes task.

> **Note**: Have a feature in mind? Feel free to comment in this issue, we will see if it can make its way to v3.

## Moving to ESM
As Node.js ecosystem is moving to ESM, it is becoming harder to rely on dependencies that works with CommonJS. As a side-effect, sometimes we cannot get security patches, or get deprecation warnings.

Moving to ESM is really not a choice. We can delay it, but it has to happen one day.

We will rewrite the Japa packages in ESM, therefore, the host application (the one using Japa) has to use ESM as well in order to import Japa inside the codebase.

## Feature requests

- [x] Support for registering multiple reporters and activating them with a config change or command line flag. This way, you have multiple reporters and switch between them based upon the current environment.

## Issues to look into

- [x] https://github.com/japa/core/issues/62
- [x] https://github.com/japa/core/issues/60

## Internals

We have to cleanup the internals of the `@japa/runner` package. Since, most of the hard work is done by `@japa/core`, I went lazy and dumped all the code of the runner package in one file.

But, I think, we should clean it up now and make it more streamlined. 

Update: The codebase is a lot cleaner and well organized now. https://github.com/japa/runner/commit/c57d3444c2bed7ff8226ce6380dfc658d33eaf74

## Releases

- https://github.com/japa/core/releases/tag/v8.0.0-0 ( Has one breaking change )
- https://github.com/japa/runner/releases/tag/v3.0.0-0 ( Has many breaking changes )

**Comment by jlenon7** [comment]
AdonisJS is a TypeScript framework, it comes with object-oriented programming style by default. So why do we need to write tests in functional style? 

I work a lot with Java too, and whenever I come to Node.js ecosystem I miss [JUnit](https://junit.org/junit5/docs/current/user-guide/#writing-tests) so much 😫. 

Japa is the best testing framework in the backend ecosystem for Node.js nowadays, and I wonder why we couldn't create TypeScript decorators for Japa to create tests using classes?

The test class would be the `test.group('${className}')` fn and the `@Test` decorator would be the `test('${methodNameOrTitle}')` fn:

```ts
export default class MyTest {
  @Test('my test title')
  public async myTest({ assert }: TestContext) {
    assert.equal(1, 1)
  }
}
```

**Comment by Julien-R44** [comment]
@jlenon7 my two cents on that: i think it's primarily a matter of language convention. in javascript, such test writing style isn't common. as far as I'm aware, none of the existing test framework allow this

and, tell me if i'm wrong, but i can't see any real advantage or disadvantage in using either one or the other. well, maybe the class-based approach is more verbose, because you need decorators for absolutely everything (tags, skip, timeout, retry etc.). so i am not sure why you are missing junit so much, i would appreciate to have your thoughts on that

otherwise i think all the APIs are open in japa to allow the emergence of a third-party lib that will use a class-based approach

**Comment by jlenon7** [comment]
> in javascript, such test writing style isn't common. as far as I'm aware, none of the existing test framework allow this

Yea, I can't find anyone too. I think writing functional tests is the common because of JavaScript. In the beginning, people didn't have TypeScript, so this pattern has been established.

> and, tell me if i'm wrong, but i can't see any real advantage or disadvantage in using either one or the other

The advantage I see when using class based tests is creating base test classes (`BaseTest`) that could have a lot of base helpers defined for each case. Like creating fake data, mocking some dependency of the IoC, generating JWT's. Other nice example would be to create a `BaseCommandTest` that would have common helpers to test commands, like a method to execute an `ace` command in a child process and return the stdout, stderr.

In the end of the day, all of these things could be done in functional style also. I think it's much more a matter of taste. I've had a lot of experience creating tests in both Java and Node.js (even more so in Node.js) and yet it feels much more natural for me to write tests in classes. The point I want to make here is the following; Since it's a matter of taste, and we already write object-oriented code, why not creating these decorators internally?

> well, maybe the class-based approach is more verbose

This depends on each person, of course, but I prefer a verbose test written with classes than one written in a functional way (I find it much easier to read and maintain).

> otherwise i think all the needed APIs are open in japa to allow the emergence of a third-party lib that will use a class-based approach

Is it possible to make Japa understand what is a class without changing the `importer` in `configure()` fn?

**Comment by thetutlage** [comment]
@ndianabasi Can you please create an issue for this with the reproduction code?

**Comment by thetutlage** [comment]
@jlenon7 As you already mentioned that it is matter a taste, so it is not possible to have something that appeals everyone.

Also, I think changing the syntax of the framework is out of the question at this stage, regardless of the merits and demerits. 

If you fancy creating a class based tests runner on top of Japa, then you need to dig into the source code of `@japa/runner` and see how it using the `@japa/core`. All the heavy lifting is done by `@japa/core`, which does not enforce any high-level API choices.

**Comment by jlenon7** [comment]
I was not talking about changing the syntax of the framework, but adding a new choice, decorators would be a plus. The user would be asked when running `npm init japa` command if he wants functional or class based tests.

The idea of creating a separate package for this is good, but I think it would make more sense to create something built-in, something like `@japa/annotations` or `@japa/decorators`. 

Perhaps I could create a POC and you guys can check them if it makes sense bringing it internally or not, what do you think?

**Comment by thetutlage** [comment]
@jlenon7 To be honest, I will not be interested in maintaining another API myself. Also, I think having it as a community package is a valuable as having it in the core. Developers who like that API will use the package and get benefited from it.

**Comment by ndianabasi** [comment]
@thetutlage, While working on a reproduction repo, I realised that I used the wrong rule. I should have used unique instead of exists. 🤦‍♂️💔

Apologies for the confusion. 😄

**Comment by thetutlage** [comment]
@ndianabasi No worries, glad it worked

**Comment by McSneaky** [comment]
@jlenon7 I don't know how much time you have, but would be cool if you can start community package for it. It's a thing that has been asked / discussed several times in Discord too, so there are some more people interested in it

**Comment by Julien-R44** [comment]
I just thought of this: it would be nice to have a system so that plugins could inject what they want into the final summary printed by the reporters.

concrete use case: in @japa/snapshot, it would be cool to display, at the end of test execution, the number of snapshots that have been updated. For example Vitest print that :
![image](https://github.com/japa/runner/assets/8337858/3f656f6e-bce6-4d99-a1dc-07a293e6198f)

we know that a snapshot comparison failed and that three snapshots are obsolete (i.e. they are present in the .ts.snap files but were not used for testing)

**Comment by thetutlage** [comment]
@Julien-R44 

<img width="618" alt="Screenshot 2023-06-27 at 1 09 53 PM" src="https://github.com/japa/runner/assets/1706381/75a3e5a5-280f-48c4-9bf2-812a953cf009">

Have not added any colors. But here is a proof of concept. The plugin will receive an instance of the `SummaryBuilder` and it can register a summary reporter with it.

Rough code.

```ts
plugins: [({ runner }) => {
  runner.summaryBuilder.use(() => {
    return [{
      key: 'Snapshots',
      value: [
        '1 Failed',
        '3 obsolete',
        'tests/suite.test.ts',
        '  * suite name > snapshot 1',
        '  * suite name > snapshot 2',
        '  * suite name > snapshot 3'
      ]
    }]
  })
}]
```

- You can give any color to the strings
- Each array item from the `value` array will be printed in its own line, respecting the indentation.

Related commit https://github.com/japa/core/commit/1144da5e5dc02eedeae70c8f8b4b85b36d1dcab0

**Comment by Julien-R44** [comment]
looks perfect. thanks dude !

**Comment by jlenon7** [comment]
Another thing that is very annoying when working with Japa is that we need to handle every minimal change in your hooks (setup, teardown, etc).

Is there any way to run each test file in a worker thread? I've tried to instantiate the `Worker` in `importer` but it throws that I can't run tests without configuring it.

It would be nice to have a plugin to avoid this behavior is certain scenarios. Do you guys have any idea on how this could be implemented?

**Comment by thetutlage** [comment]
@jlenon7 Not sure what you mean by "handle every minimal change in your hooks" and how running in worker threads is related to that.

Can you share some examples of the same?

**Comment by jlenon7** [comment]
Let's suppose I'm working with environment variables and configuration files. In `setup()` I would need to load the envs and configuration files, while in `teardown()` I would need to unload everything. If I don't do that, the behavior of the test will leak to the other one.

Another example is if I'm using decorators, I should always delete the metadata of decorated classes, which is very difficult to do as the application grows.

As mentioned before, everything could be handled in test hooks, but with worker threads we would have a clean environment for each test to run, leaving our test hooks cleaner with what is really worth running.

**Comment by davidharting** [comment]
I am curious what the Japa core team thinks of the new native node test runner. 

Do you imagine a future in Japa v4 for example where Japa integrates with Node.js test runner instead of a custom runner?

I love that the Japa team is so committed to making Node.js more capable, so I wonder if leaning into and enhancing native node functionality could make sense for this project.

**Comment by MANTENN** [comment]
@thetutlage are there any plans to change the return type of pluginfn from void to the type the plugin passes as a generic.

For ex: ```typescript
export type PluginFn = (
  config: Required<Config>,
  runner: Runner,
  classes: {
    Test: typeof Test
    TestContext: typeof TestContext
    Group: typeof Group
  }
) => void | Promise<void>
```

Would be:
```typescript

export type PluginFn = <T>(
  config: Required<Config>,
  runner: Runner,
  classes: {
    Test: typeof Test
    TestContext: typeof TestContext
    Group: typeof Group
  }
) => T | Promise<T>
```

This way we can easily extend chai and expect with custom modules such as [jest-json-schema](https://www.npmjs.com/package/jest-json-schema).

Currently, I get the prototype of expect to add jest-json-schema and add a type declaration provided by jest-json-schema to extend:

```typescript
export const extendExpectWithJsonSchemaMatch = () => (_config: Required<Config>, _runner: Runner, classes: Classes) => {
  const expect = classes.TestContext.prototype.expect

  ApiResponse.macro('expect', function (_expectedValue) {
    return expect(_expectedValue);
  })
  ApiResponse.macro('toMatchSchema', function (matchSchema) {
    return expect(this.body()).toMatchSchema(matchSchema)
  })
  // TestContext created with https://www.npmjs.com/package/macroable
  // so we can tap into prototype after expect plugin has been loaded to add any plugin
  expect.extend(matchers)
  // have to export expect here
  return expect;
}
```

```typescript
import { Expect } from "@japa/expect";

declare module 'expect' {
  interface AsymmetricMatchers {
    toMatchSchema(schema: object): void;
  }
  interface Matchers<R> {
    toMatchSchema(schema: object): R;
  }
}

declare module '@japa/api-client' {

  interface ApiResponse {
    toMatchSchema(schema: object): this
    expect<T = unknown>(actual: T): ReturnType<Expect>
  }
}

export { };

```

**Comment by thetutlage** [comment]
Alright, so Japa v3 is out as a stable release.

> [!IMPORTANT]
> If you are using AdonisJS, you must stick with Japa v2 for a while, because v3 is ESM only and AdonisJS v5 apps uses CommonJS. 
> This is going to be a theme for the coming month as we start releasing everything approaching towards AdonisJS v6 release.

## Sticking with older version?

- You can access the docs for Japa v2 here. http://v2.japa.dev/
- New AdonisJS projects will scaffold the application with Japa v2.

That's pretty much all!

## Ready to migrate to v3?

- The new docs are available at japa.dev
- Here's the link to upgrade guide. 

## Facing issues?

- Just report them in the relevant repos and we will try to get back to them ASAP.

Enjoy your weekend 🏝️
